### ISSUE TITLE
Use of unresolved identifier "SuggestionTableRow"

### ISSUE THREAD

**Issue by TCOA** [EurekaCommunity/SuggestionRow#10]
Perhaps this could be titled simply "More Clear Usage Instructions for Getting Started".......

I have followed what I understand to be the usage instructions:
(sorry, for clarity as a newbie in Swift {5 weeks and counting...}, I will use terms that I understand)

1. In my podfile, I have 
pod 'Eureka', '-> 3.0'
(previously I had 2.0.0-beta.1 - that didn't work, either...)
I ran pod update after changing to 3.0 and no update was done (still shows "Using Eureka (2.0.1)")

2. in the 'general' area (above the classes), I have:
import Eureka 
the 'public protocol' function (from the readme page)
the 'struct Scientist' (from the readme page)
the 'extension Scientist' (from the readme page)
the 'func ==' (from the readme page)

all this has no errors

3. in viewDidLoad, after super.viewDidLoad(), I have:
let users: (from the readme page)

4. inside the form (where everything else works fine), I have:
the  <<< SuggestionTableRow<Scientist>() { function (from the readme page)

And, this is where I get the error 'Use of unresolved identifier "SuggestionTableRow"'

I'm only trying to get the examples working so I can make the mods I need for my row (looking to use Mapbox instead of Google for address lookups), but obviously missing something somewhere......

From what I understand, this should be part of Eureka (which I'm using a lot), though this identifier just isn't working for me.

Your guidance on what I need to do to get this working is most appreciated.

**Comment by mats-claassen** [comment]
SuggestionRow is not included in `Eureka`. It is also not yet compatible with Cocoapods although that is something which we should address.

Currently to use SuggestionRow you must add its sources (excluding the Example code) to your project manually.

**Comment by mats-claassen** [comment]
@lognaturel What do you think of adding this to Cocoapods?

**Comment by lognaturel** [comment]
I think that'd be fantastic @mats-claassen. I had high hopes for contributing to Eureka and this row but the project I use it in a half-converted-to-swift-3/not-compiling kind of state and I sadly haven't had time to even get it back on its feet.

I just noticed that you didn't have commit privileges and gave them to you. In general, I'm happy for others to take this over for now and hope I can be back soon!

**Comment by mats-claassen** [comment]
SuggestionRow has been on Cocoapods for over a year so this issue is fixed.
