### ISSUE TITLE
Unresolved Identifier SuggestionAccessoryRow

### ISSUE THREAD

**Issue by martheli** [EurekaCommunity/SuggestionRow#14]
After using Cocoapods to install SuggestionRow I am receiving this error with the following:

```
 form +++ Section("Input accessory view suggestions")
            <<< SuggestionAccessoryRow<String>() {
                $0.filterFunction = { text in
                    options.filter({ $0.hasPrefix(text) })
                }
                $0.placeholder = "Enter text that starts with A..."
            }
```

I have Eureka imported and other form is working well.

**Comment by mats-claassen** [comment]
I would think this is a compiler issue or probably something unrelated to the message itself. Have you checked if there was any other compiler issue in that file?

**Comment by lis186** [comment]
Do you import SuggestionRow? @martheli
