### ISSUE TITLE
Request: Add Carthage support

### ISSUE THREAD

**Issue by sverin** [EurekaCommunity/SuggestionRow#17]
Is it possible to att Carthage support for this library?

**Comment by marbetschar** [comment]
https://github.com/EurekaCommunity/SuggestionRow/pull/20

**Comment by macfurin** [comment]
Is it possible to make a release with Carthage support please ?

**Comment by mats-claassen** [comment]
Working on it

**Comment by mats-claassen** [comment]
Version 2.1.0 has just been released!

I am closing this issue. If any new problems arise please open a new one
