### ISSUE TITLE
Swift 4?

### ISSUE THREAD

**Issue by grimmwerks** [EurekaCommunity/SuggestionRow#18]
Any chance on getting an update?

**Comment by marbetschar** [comment]
https://github.com/EurekaCommunity/SuggestionRow/pull/19

**Comment by dote** [comment]
Hi, do does one use SuggestionRow with Eureka 4.0.1? Sorry, not sure where best to ask. Thank you.

**Comment by marbetschar** [comment]
@dote I tested it one month ago and it worked quite well. If I remember correctly even without my pull request. Just give it a shot ;)

**Comment by dote** [comment]
Good morning @marbetschar I tried adding it to my podfile. It complains that the versions are mismatched (v3 vs v4) so it doesn't work. If I subsequently go with Eureka 3 instead of 4.0.1, my app spews a gazillion errors... thoughts?

**Comment by marbetschar** [comment]
Unfortunately I can‘t help out with Cocoapods. Ran into countless Problems in the past using Cocoapods - no clue why - and decided to move on to Carthage.

**Comment by dote** [comment]
Are there instructions on including SuggestionRow manually?

**Comment by marbetschar** [comment]
@dote this should be pretty straight forward: Add Eureka to your pods and simply copy & paste the Source code from the  SuggestionRow project which is stored in Sources/

**Comment by dote** [comment]
@marbetschar thank you so much, that worked!
