### ISSUE TITLE
Add Readme

### ISSUE THREAD

**Issue by mats-claassen** [EurekaCommunity/SuggestionRow#2]
Hi @lognaturel I think this repository should have a ReadMe explaining its features and how to use it. 

What do you think? Do you plan to add it?

**Comment by lognaturel** [comment]
I won't have time to generalize this as requested any time soon. Should I just take the project down in the mean time or add a simple readme about how it functions as it is with just `String` suggestions?

**Comment by mats-claassen** [comment]
I can try generalize this row and submit a pull request. 
We could wait and add the Readme after that.

**Comment by lognaturel** [comment]
That sounds great. I think I'll learn some useful things from seeing how you prefer to do things like specifying the filter function and then I can take a stab at the Readme.
