### ISSUE TITLE
Please update the SuggestionRow.podspec file to support Eureka 4

### ISSUE THREAD

**Issue by andreykats** [EurekaCommunity/SuggestionRow#22]
Cocopods is throwing a dependency error.

Please update the dependencies list in SuggestionRow.podspec to support Eureka version higher than 3.0.

  "dependencies": {
    "Eureka": [
      ">= 3.0"
    ]

Thanks!

**Comment by mats-claassen** [comment]
Updated in branch `version-change`. Does it work for you?

**Comment by ojas05** [comment]
I am also facing the same issue like AndreyKats. Please update the suggestion row dependency to Eureka 4.0

**Comment by mats-claassen** [comment]
Did you try with the `version-change` branch? It worked for me. I have merged it now so that `master` should be ok.

If it works for you with master and running `pod update SuggestionRow` then I can release it.
