### ISSUE TITLE
[SuggestionTableRow] Can't enter values other than suggested by autocomplete

### ISSUE THREAD

**Issue by fastboatster** [EurekaCommunity/SuggestionRow#23]
I was looking at the example project and when I tried to type anything besides suggested scientists (say, Nicola Tesla) into Suggestion Table Row, it would disappear after I hit Done on the keyboard. I want to be able to enter any values I want, not just the suggested ones. Is there a way to do that?

**Comment by mats-claassen** [comment]
To get that you must implement the `init?(string:)` function of `InputTypeInitiable` protocol and create a scientist from that string

**Comment by fastboatster** [comment]
OK, thank you, I'll try that

**Comment by amirfl** [comment]
I had the same issue solved by using a String as the row value type (instead of a struct like Scientist in the example)
