### ISSUE TITLE
Support for Carthage and Swift 4.2

### ISSUE THREAD

**Issue by macfurin** [EurekaCommunity/SuggestionRow#28]
When building scheme "SuggestionRow" with Carthage, throw an error :

`error: /Users/username/Xcode Projects/Noty/Carthage/Checkouts/SuggestionRow/Pods/Target Support Files/Pods-SuggestionRow/Pods-SuggestionRow.release.xcconfig: unable to open file (in target "SuggestionRow" in project "SuggestionRow") (in target 'SuggestionRow')`

Is it possible to release a new version with last commits and build fixes please ?

Thanks for these great job

**Comment by mats-claassen** [comment]
We will be updating all Eureka custom rows once a new Eureka version is released
