### ISSUE TITLE
Examples of custom suggestion rows? 

### ISSUE THREAD

**Issue by jrahaim** [EurekaCommunity/SuggestionRow#31]
I found this: 

> If you want to change these cells drastically, create your own row with your own cell class which conforms to EurekaSuggestionTableViewCell.

To be a little to simplified for me.. I have this working, except for my need to customize the search results cells.

**Comment by mats-claassen** [comment]
Hi @jrahaim I updated the Readme with an example of how to subclass the row. Tell me if that is helpful.

In your case, you need to subclass `SuggestionTableViewCell` which are the search results cells. You can also load this from a Nib (with some changes to `SuggestionTableCell`)

**Comment by sarrathy** [comment]
Can you help me in how to customize the textfield .
