### ISSUE TITLE
how to use asyncFilterFunction

### ISSUE THREAD

**Issue by sarrathy** [EurekaCommunity/SuggestionRow#39]
Can u give a example on how to use asyncFilterFunction . I want to call a API to get the suggestion and then display suggestion . i Am not getting how to use the asyncFilterFunction. 

 var completionHandler: ([Scientist])->Void = { text in                    
 }

 $0.asyncFilterFunction = { (text, completionHandler) in
                    
 }

Not sure if the above code is correct . how to pass and call the completionHandler .

**Comment by mats-claassen** [comment]
You can use it like this: 

```swift
<<< SuggestionTableRow<Scientist>() {
    $0.asyncFilterFunction = { text, completionHandler in
        // do async work and then call completionHandler
        DispatchQueue.main.asyncAfter(deadline: .now() + 2, execute: {
            let results = users.filter({ $0.firstName.lowercased().contains(text.lowercased()) })
            completionHandler(results)
        })
    }
    $0.placeholder = "Search for a famous scientist"
}
```

Instead of the `DispatchQueue.main.asyncAfter`, do your async work and when it finishes call `completionHandler` with the results.
You might want to throttle requests with a timer if you are going to do network calls in this function.

**Comment by sarrathy** [comment]
Thanks a lot
