### ISSUE TITLE
iOS 13 Dark Mode

### ISSUE THREAD

**Issue by kamerc** [EurekaCommunity/SuggestionRow#43]
FYI that I have implemented the needed changes for SuggestionRow at https://github.com/kamerc/SuggestionRow/tree/ios-13. Don't want anyone to have to do duplicate work. I cannot submit a pull request until Eureka dark mode changes have been officially released. Right now SuggestionRow is pointing to my base Eureka fork that has the dark mode changes

**Comment by jdanthinne** [comment]
The `xcode11` branch of Eureka now supports Dark Mode. Perhaps a good time to test your PR…

**Comment by jdanthinne** [comment]
Dark Mode for Eureka officially released…

**Comment by kamerc** [comment]
Thanks, I will look at it by the end of this week

**Comment by kamerc** [comment]
Pull request has now been submitted https://github.com/EurekaCommunity/SuggestionRow/pull/45
