### ISSUE TITLE
SuggestionTableRow behind keyboard

### ISSUE THREAD

**Issue by diegogarciar** [EurekaCommunity/SuggestionRow#44]
Hello,
When using the SuggestionTableRow on a MultivaluedSection with enough rows to fill the screen, the suggestion table sits behind the keyboard and suggestions are not shown.
I attached a photo of the actual screen and another one from the debug hierarchy

<img width="273" alt="Screen Shot 2019-10-03 at 11 55 43" src="https://user-images.githubusercontent.com/17276155/66151570-d91e9b80-e5d4-11e9-8071-306b8d8437af.png">

<img width="273" alt="Screen Shot 2019-10-03 at 11 55 43" src="https://user-images.githubusercontent.com/17276155/66151929-8beef980-e5d5-11e9-92bc-169f3a2373db.png">

**Comment by andrey-zelenin** [comment]
Hi, any solution?

**Comment by diegogarciar** [comment]
Hey @andrey-zelenin, I ended up using the other row: SuggestionAccessoryRow. And customized the row a little

**Comment by andrey-zelenin** [comment]
Thanks @diegogarciar, I'll try to do the same

**Comment by chickendiver** [comment]
Any updates on this?

**Comment by nicolantean** [comment]
Hi @chickendiver, the issue you have could be fixed in your FormViewController. This is a possible solution for the issue:
```
override func textInputDidEndEditing<T>(_ textInput: UITextInput, cell: Cell<T>) where T : Equatable {
        if cell is SuggestionCell<Scientist> {
            tableView.contentInset = .zero
        }
}
override func textInputDidBeginEditing<T>(_ textInput: UITextInput, cell: Cell<T>) where T : Equatable {
        if cell is SuggestionCell<Scientist> {
            tableView.contentInset = UIEdgeInsets(top: 0, left: 0, bottom: 500, right: 0)
        }
}
```
Notice that you have to adapt the bottom value in the content inset depending on your project and device. Also, you can implement a different solution using the scrollToRow function.

**Comment by chickendiver** [comment]
Excellent, thank you. This worked!

**Comment by mats-claassen** [comment]
Closed as solved. Thanks @nicolantean
