### ISSUE TITLE
Release needed

### ISSUE THREAD

**Issue by kamerc** [EurekaCommunity/SuggestionRow#53]
Can we get a new release published? The last release was 2/2020 and there have been several PRs since then including updating Eureka. @mats-claassen

**Comment by mats-claassen** [comment]
🎉  Congrats

 🚀  SuggestionRow (3.3.0) successfully published
 📅  July 27th, 09:49
 🌎  https://cocoapods.org/pods/SuggestionRow
 👍  Tell your friends!
